kyverno:
  enabled: false
replicaCount: 1

service:
  type: ClusterIP
services:
  vote:
    # Only vote needs a public endpoint for DNS failover and user traffic.
    type: LoadBalancer
  result:
    # Keep result private on Azure student subscriptions to avoid public IP quota.
    type: ClusterIP

ingress:
  enabled: false
  className: ""
  hosts:
    vote: vote-azure.example.com
    result: result-azure.example.com

images:
  vote:
    repository: devsecopsvotingacrfi1hac.azurecr.io/voting-app-vote
    tag: 00e5e507649bc395affb651ba847880fa36fbdf8
    digest: sha256:6719df473161d19481d8f3009b76f0a2edaa577646cbb66c62aca638803ebb2d
  result:
    repository: devsecopsvotingacrfi1hac.azurecr.io/voting-app-result
    tag: 00e5e507649bc395affb651ba847880fa36fbdf8
    digest: sha256:a52d74dc35ce13cd9671e09efd24aff6d5cdbc242c195ba67a7d04c461f0a381
  worker:
    repository: devsecopsvotingacrfi1hac.azurecr.io/voting-app-worker
    tag: 00e5e507649bc395affb651ba847880fa36fbdf8
    digest: sha256:04692e8109013fe3456ad1a55bdb9368aac12116c106d669389c94e2c70c1634
  redis:
    repository: redis
    tag: 7-alpine
  db:
    repository: postgres
    tag: 15-alpine

appSecretName: voting-app-runtime

serviceAccounts:
  vote:
    name: vote-sa
    annotations: {}
  result:
    name: result-sa
    annotations: {}
  worker:
    name: worker-sa
    annotations: {}

localDependencies:
  enabled: false
  redis:
    enabled: true
externalSecret:
  enabled: true
  storeName: azure-key-vault
  remoteKey: voting-app-runtime

monitoring:
  enabled: false
  prometheusRelease: kube-prometheus-stack
  slo:
    successRateTarget: 0.99
    p95LatencySeconds: 0.5
    alertFor: 1m

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

resources:
  vote:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
  result:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
  worker:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
