kyverno:
  enabled: true
replicaCount: 1

service:
  # LoadBalancer exposes a public IP on AKS so DNS failover can point traffic here
  type: LoadBalancer

ingress:
  enabled: false
  className: ""
  hosts:
    vote: vote-azure.example.com
    result: result-azure.example.com

images:
  vote:
    repository: devsecopsvotingacrfi1hac.azurecr.io/voting-app-vote
    tag: e96b6acb4e1abdeb8273c0a55af71233069ccbe3
    digest: sha256:89b8ad02b4255c49dab0937f416dcc1ed3952240969de09121ecb7a731b10c6a
  result:
    repository: devsecopsvotingacrfi1hac.azurecr.io/voting-app-result
    tag: e96b6acb4e1abdeb8273c0a55af71233069ccbe3
    digest: sha256:0e9c811e4f13a44a82040cf153854008d4abe003f01125cc0b0fa129ebc84293
  worker:
    repository: devsecopsvotingacrfi1hac.azurecr.io/voting-app-worker
    tag: e96b6acb4e1abdeb8273c0a55af71233069ccbe3
    digest: sha256:3ab0b145c47ae9a8e39560266832b985a3711dab9c974988b34b4582678bce9d
  redis:
    repository: redis
    tag: 7-alpine
  db:
    repository: postgres
    tag: 15-alpine

appSecretName: voting-app-runtime

serviceAccounts:
  vote:
    name: vote-sa
    annotations: {}
  result:
    name: result-sa
    annotations: {}
  worker:
    name: worker-sa
    annotations: {}

localDependencies:
  enabled: false
externalSecret:
  enabled: true
  storeName: azure-key-vault
  remoteKey: voting-app-runtime

monitoring:
  enabled: false
  prometheusRelease: kube-prometheus-stack
  slo:
    successRateTarget: 0.99
    p95LatencySeconds: 0.5
    alertFor: 1m

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

resources:
  vote:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
  result:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
  worker:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi

