replicaCount: 3

service:
  type: LoadBalancer

ingress:
  enabled: false
  className: ""
  hosts:
    vote: vote.example.com
    result: result.example.com

images:
  vote:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-vote
    tag: 269379c781f3376a9374c03c4b41b52cd5681ace
    digest: sha256:518a8332993a564a0b027baaa50802a935807446780d8d960bac28850f885d74
  result:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-result
    tag: 269379c781f3376a9374c03c4b41b52cd5681ace
    digest: sha256:d944ea36190ee0606fffd0d2013ce391e5813e647f800573f9d1dce2ea35b0af
  worker:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-worker
    tag: 269379c781f3376a9374c03c4b41b52cd5681ace
    digest: sha256:bb4f31fbe86644df54c57d03272be6487bee61815f9beb1a024b8dfa0b980806
  redis:
    repository: redis
    tag: 7-alpine
  db:
    repository: postgres
    tag: 15-alpine

appSecretName: voting-app-runtime

serviceAccounts:
  vote:
    name: vote-sa
    annotations: {}
  result:
    name: result-sa
    annotations: {}
  worker:
    name: worker-sa
    annotations: {}

localDependencies:
  enabled: false
externalSecret:
  enabled: true
  storeName: aws-secrets-manager
  remoteKey: devsecops-voting/app-runtime

monitoring:
  enabled: true
  prometheusRelease: kube-prometheus-stack
  slo:
    successRateTarget: 0.99
    p95LatencySeconds: 0.5
    alertFor: 1m

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

resources:
  vote:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  result:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  worker:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
