kyverno:
  enabled: true
replicaCount: 1

service:
  # LoadBalancer exposes a public IP on AKS so DNS failover can point traffic here
  type: LoadBalancer

ingress:
  enabled: false
  className: ""
  hosts:
    vote: vote-azure.example.com
    result: result-azure.example.com

images:
  vote:
    repository: devsecopsvotingacrfi1hac.azurecr.io/voting-app-vote
    tag: 71288166741d46e8b263986b8c8891b9ca6b9f7c
    digest: sha256:95299a936f99978dcf496a67085b1560bd102cc349bdc442a93e03cf5b2bfabb
  result:
    repository: devsecopsvotingacrfi1hac.azurecr.io/voting-app-result
    tag: 71288166741d46e8b263986b8c8891b9ca6b9f7c
    digest: sha256:231fb1486cc5e18e8c75b908ab397e1d356b19902cdafe42cba611dcad46880e
  worker:
    repository: devsecopsvotingacrfi1hac.azurecr.io/voting-app-worker
    tag: 71288166741d46e8b263986b8c8891b9ca6b9f7c
    digest: sha256:e6ff124e523300d1ec7b6636613cee3045f676e67d5123a3ffef612d8f93ac19
  redis:
    repository: redis
    tag: 7-alpine
  db:
    repository: postgres
    tag: 15-alpine

appSecretName: voting-app-runtime

serviceAccounts:
  vote:
    name: vote-sa
    annotations: {}
  result:
    name: result-sa
    annotations: {}
  worker:
    name: worker-sa
    annotations: {}

localDependencies:
  enabled: false
externalSecret:
  enabled: true
  storeName: azure-key-vault
  remoteKey: voting-app-runtime

monitoring:
  enabled: false
  prometheusRelease: kube-prometheus-stack
  slo:
    successRateTarget: 0.99
    p95LatencySeconds: 0.5
    alertFor: 1m

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

resources:
  vote:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
  result:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
  worker:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi

