replicaCount: 3

service:
  type: LoadBalancer

ingress:
  enabled: false
  className: ""
  hosts:
    vote: vote.example.com
    result: result.example.com

images:
  vote:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-vote
    tag: 6ae2fb452d7314491271ca40c1b26454e6dd6a03
    digest: sha256:4f17f781191a9fefd7ab65fd0c1a5af6b94b6ffd73707ca7b4bf73d40eb9db8e
  result:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-result
    tag: 6ae2fb452d7314491271ca40c1b26454e6dd6a03
    digest: sha256:e354346a3c36f92ebc235a39271f7a19fb050bd25ac7bdf1c51fac6ac5256612
  worker:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-worker
    tag: 6ae2fb452d7314491271ca40c1b26454e6dd6a03
    digest: sha256:ac282be7cd1a38a0bf094c42bf17f65a114afd634fd08981f855ac31920133f7
  redis:
    repository: redis
    tag: 7-alpine
  db:
    repository: postgres
    tag: 15-alpine

appSecretName: voting-app-runtime

serviceAccounts:
  vote:
    name: vote-sa
    annotations: {}
  result:
    name: result-sa
    annotations: {}
  worker:
    name: worker-sa
    annotations: {}

localDependencies:
  enabled: false
externalSecret:
  enabled: true
  storeName: aws-secrets-manager
  remoteKey: devsecops-voting/app-runtime

monitoring:
  enabled: true
  prometheusRelease: kube-prometheus-stack
  slo:
    successRateTarget: 0.99
    p95LatencySeconds: 0.5
    alertFor: 1m

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

resources:
  vote:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  result:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  worker:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

kyverno:
  enabled: true
